# Generated by Django 4.2.15 on 2024-08-14 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('std', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='posted_by',
            field=models.ForeignKey(limit_choices_to={'status': 'cdf'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='bursary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bursary'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std.student'),
        ),
    ]
