# Generated by Django 5.1 on 2024-08-09 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='posted_by',
            field=models.ForeignKey(limit_choices_to={'status': 'cdf'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='bursary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bursary'),
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.application'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='bursary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bursary'),
        ),
    ]
