# Generated by Django 4.2.15 on 2024-08-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='answers',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
