# Generated by Django 4.2.15 on 2024-08-09 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
